### PR TITLE
Update Austrian and IBFD styles

### PR DESCRIPTION
**Pull request by georgd**

### CODE REVIEW

**Comment by bwiernik** [comment]
@georgd Is there someone you know other than Frank who could review these, at least for accuracy?

**Comment by georgd** [comment]
You mean syntactically? Unfortunately, no. I'm relying on constantly
validating against the schema.

On checking for correct output, I'm working together with some legal
scholars here, but they're all beginners with Jurism as I only began
introducing it in Austria five months ago.

Brenton M. Wiernik ***@***.***> schrieb am Do., 1. Apr. 2021,
16:57:

**Comment by bwiernik** [comment]
No, I meant in terms of correct output. I can review for syntax/style, but don't have the knowledge to evaluate output.

**Comment by georgd** [comment]
I'll push the updated tests which I use for testing with
citeproc-test-runner later today or tomorrow. They mainly are copied from
the style manuals.

Brenton M. Wiernik ***@***.***> schrieb am Do., 1. Apr. 2021,
17:51:

**Comment by georgd** [comment]
The style tests are updated in https://github.com/georgd/jm-style-tests/tree/jm-legcit, https://github.com/georgd/jm-style-tests/tree/jm-ibfd and https://github.com/georgd/jm-style-tests/tree/jmAzr (Some tests are failing for technical reasons, for others (UN.int case law), sources are ambiguous.

**Comment by georgd** [comment]
@bwiernik what do you propose for getting on with this?

**Comment by bwiernik** [comment]
This looks okay to me. Let me know when you think it's good to merge.

**Comment by georgd** [comment]
Thank you! I'm currently preparing a workshop and fixing some edge cases on the way. I'll be done tomorrow and will notify you then.

**Comment by georgd** [comment]
It’s ready to merge now.

**Pull request merged**
